# Use root/example as user/password credentials
version: '3.8'

services:
  cliente:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - network

  server:
    image: gabrielarriola/api-examen
    ports:
      - "8080:8080"
    networks:
      - network

networks:
  network: